apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: paulosarmento/gitopsfc
  newTag: 5b543e44c5dd58f9a6bc38a1b1278162f67c4f4b
